### ISSUE TITLE
composer  install fail 

### ISSUE THREAD

**Issue by heartshare** [loveorigami/yii2-plugins-system#1]
# composer require "loveorigami/yii2-plugins-system": "*"

  [InvalidArgumentException]
  Could not find package \* at any version for your minimum-stability (stable)

I got the error, any updates ? thanks

**Comment by loveorigami** [comment]
Try it
`"loveorigami/yii2-plugins-system": "1.0-rc"` as on packagist https://packagist.org/packages/loveorigami/yii2-plugins-system#1.0-rc
or
I think, you need add this package file in composer to dev section

``` php
  "require-dev": {
    "yiisoft/yii2-codeception": "*",
    "yiisoft/yii2-debug": "*",
    "yiisoft/yii2-gii": "*",
    "yiisoft/yii2-faker": "*",
    "loveorigami/yii2-plugins-system": "*"
  },
```

or in composer file change minimum stability to dev
`"minimum-stability": "dev",`

**Comment by heartshare** [comment]
Yes, ok now 
"minimum-stability": "dev", + "loveorigami/yii2-plugins-system": "*"
thanks
