### ISSUE TITLE
Ошибка в миграциях

### ISSUE THREAD

**Issue by developeruz** [loveorigami/yii2-plugins-system#17]
Добрый день. Не получается запустить миграции, пишет:
`Migration failed. Directory specified in migrationPath doesn't exist: @vendor/loveorigami/yii2-plugins-system/migrations`
если запустить как  
`php yii migrate/up --migrationPath=@vendor/loveorigami/yii2-plugins-system/src/migrations`
то файлы миграций находит, но выполнить не может, т.к при создании класса миграции не видит (скорее всего из-за namespace)
`Class 'm170105_094230_drop_tables' not found`
Не могли бы удалить namespace из миграций или подсказать как решить проблему?

**Comment by loveorigami** [comment]
Попробуйте настройку с namespace
http://www.yiiframework.com/doc-2.0/guide-db-migrations.html#namespaced-migrations

**Comment by developeruz** [comment]
Да, спасибо, так сработало.
