### ISSUE TITLE
yii2-plugins-system

### ISSUE THREAD

**Issue by aleksandrhorkavyi** [loveorigami/yii2-plugins-system#19]
Добрый день! 
Подскажите пожалуйста, установленное расширение подключает новые или встроенные шорткоды и плагины нормально, все как в гайде)
![image](https://user-images.githubusercontent.com/23636333/31538618-cf9bcc02-b00e-11e7-9fc2-ef25b1864ec2.png)
но вместо того, чтобы обработать и отобразить во вьюшке результат, выводит только 
![image](https://user-images.githubusercontent.com/23636333/31538787-4f0aa6ac-b00f-11e7-90f0-9b3f69ace87f.png)
или
![image](https://user-images.githubusercontent.com/23636333/31538798-5d75dd24-b00f-11e7-8814-9a6ecc42f287.png)

**Comment by loveorigami** [comment]
Подключает все, Но нужно указать папку, в которой будут хранится ваши плагины с шорткодами
```
        'pluginsDir'=>[
            '@lo/plugins/core', // default dir with core plugins
            // '@common/plugins', // dir with our plugins
        ]
```

**Comment by loveorigami** [comment]
далее для шорткодов - https://github.com/loveorigami/yii2-shortcodes-pack/blob/master/docs/create_shortcode.md

для плагинов - https://github.com/loveorigami/yii2-plugins-system/blob/master/docs/create_plugin.md

**Comment by loveorigami** [comment]
Неправильно понял вопрос. У вас они не рендерятся.

На самой вкладке "Шорткоды" они включены?

Внимательно проверьте конфиг, Возможно, что-то где то упустили.
Посмотрите, как пример
https://github.com/developeruz/yii-kit/commit/5e47c0c629805fe0f7ecc8c7443ccf41381c005d 

Да и результат рендера шорткода можно увидеть на фронтенде, а не в бакенде.

**Comment by aleksandrhorkavyi** [comment]
Да, я уже решил проблему, я в конфиге немного ошибочка допустил)
Извините что побеспокоил.
p.s. классный у Вас проект)

13 окт. 2017 г. 14:33 пользователь "Andrey" <notifications@github.com>
написал:
