### ISSUE TITLE
Installed the plugin system and install core hello plugins get errors

### ISSUE THREAD

**Issue by heartshare** [loveorigami/yii2-plugins-system#2]
PHP Notice – yii\base\ErrorException

Undefined index: lo\plugins\plugins\httpauth\Httpauth

![error](https://cloud.githubusercontent.com/assets/919188/9307976/ee798468-4533-11e5-99a5-46f72e56a9ca.jpg)

**Comment by loveorigami** [comment]
1. Our config, please. 
   See as in https://github.com/loveorigami/yii2-plugins-system#3-configure-application
2. And database with plugins table

**Comment by heartshare** [comment]
i checked again , seems setting correct @@

**Comment by heartshare** [comment]
Yes , fixed many thanks :+1:
