### ISSUE TITLE
Call Instance parse?

### ISSUE THREAD

**Issue by daunt** [loveorigami/yii2-plugins-system#20]
how to call instance parsing shortcode like example bellow?
ex: \lo\plugins\core\ShortcodeHandler::parseShortcodes('[gallery id="2"]')

the problem when calling a shortcode inside which there is a shortcode
only displays shortcode strings

**Comment by loveorigami** [comment]
You can create "gallery" shortcode and install it in system.
For example, see https://github.com/loveorigami/yii2-shortcodes-pack/blob/master/src/web/youtube/YoutubeShortcodes.php#L32

For this shortcode you also create widget
https://github.com/loveorigami/yii2-shortcodes-pack/blob/master/src/web/youtube/YoutubeWidget.php

with your logic for display gallery by id or category_id

**Comment by daunt** [comment]
gallery already installed.. 
i have 2 shortcodes (gallery and user). inside logic user i put shortcodes gallery 
to show each galleries created by user.
my problem gallery output only  shortcode strings (cant parse gallery shortcodes).
how to solve that?
is there instance method to call directly shortcode? then i can put it into logic user widget to parse galley shortcode.

**Comment by loveorigami** [comment]
My variant for gallery shortcode
https://github.com/loveorigami/lo-module-gallery/tree/master/src/plugins/gallery
Widget
https://github.com/loveorigami/lo-module-gallery/blob/master/src/widgets/GalleryById.php

I think, better create shortcode as 
`[gallery id=1 user=5]`
and find in widget all photos from gallery 1 for user 5
such as
https://github.com/loveorigami/lo-module-gallery/blob/master/src/widgets/GalleryById.php#L120
```
/** @var GalleryCat $model */
            $model = $entity::find()->where(['id' => $this->id])->limit(1)->published()->one();
            if ($model) {
                /** @var ImageRepository $gallery */
                $gallery = $model->getBehavior($model::GALLERY_ONE);
                $query = $gallery->findImages()->published();
                $query->limit($this->limit);

// and your condition
                $query->andWhere(['user_id'=>$this->user])
}
```
