### ISSUE TITLE
error using with kartik-v/yii2-app-practical-a

### ISSUE THREAD

**Issue by quasiperfect** [loveorigami/yii2-plugins-system#3]
i get the error Accessing static property lo\plugins\components\EventBootstrap::$appId as non static
using with kartik-v/yii2-app-practical-a

any idea what is wrong ?

**Comment by loveorigami** [comment]
I have this error on php 5.4 in this line https://github.com/loveorigami/yii2-plugins-system/blob/master/components/EventBootstrap.php#L65

On php 5.5 works fine.

You can check it?

**Comment by quasiperfect** [comment]
hi

thanks for the update @loveorigami 

almost fixed
you have another error in Code plugin
call_user_func() expects parameter 1 to be a valid callback, non-static method lo\plugins\plugins\code\Code::shortCode() should not be called statically

**Comment by loveorigami** [comment]
Thanks, I am also see it on frontend.
